### PR TITLE
Update to 1.19.0 release

### PR DESCRIPTION
**Pull request by kynan**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@kynan I'm not sure how, how adding you to maintainers works in terms of syncronization. It might need another empty commit to get circle-ci running. 

@ocefpaf probably knows more.

**Comment by kynan** [comment]
@kmuehlbauer Yeah, not sure why circle-ci didn't kick off.

**Comment by kmuehlbauer** [comment]
@kynan Could you try to login to CircleCI with your github credentials (conda-forge).

Then goto add-projects page (https://circleci.com/add-projects) and check wether you are following `ecmwf_gribapi`. There have been some changes in CircleCi lately, which are producing this behaviour.

**Comment by kynan** [comment]
@kmuehlbauer OK, I've done that.  Do you want me to push another dummy commit? Or are you happy to merge and we'll see if circle runs off master?

**Comment by kmuehlbauer** [comment]
:grimacing: Try a dummy commit first, just to see, if this works now...

**Comment by kynan** [comment]
Hmm, apparently not...

**Comment by kmuehlbauer** [comment]
@kynan Hmm, this didn't work. I think we are safe to merge this, because this will create a new version. Hopefully Circle will run on master.

**Comment by kynan** [comment]
It did on your earlier merge.

**Comment by kmuehlbauer** [comment]
Yeah, maybe it was the timely flow of the whole thing...

**Comment by kynan** [comment]
It's running now, let's see what happens.

**Comment by kmuehlbauer** [comment]
Keeping fingers crossed...

**Comment by kmuehlbauer** [comment]
@kynan BTW, are you involved with ecmwf/eccodes development somehow or other?

**Comment by kynan** [comment]
Not directly. But Shahram isn't using GitHub or conda, so it makes more sense for me to do this.

**Comment by kmuehlbauer** [comment]
OK, nevertheless it's good to have you here :+1: 

The Circle builds are already done, Travis is in the queue. So, seems that 1.19.0 is rolling out smoothly.

**Pull request merged**
